### ISSUE TITLE
SURVIVOR filter removing all SV's and receiving error message

### ISSUE THREAD

**Issue by alpreyes** [fritzsedlazeck/SURVIVOR#36]
Hello,

I'm trying to use the SURVIVOR filter function to remove SV's from a vcf file. Here is the command I am using with the file names removed:

`SURVIVOR filter <input.vcf> <remove.bed> 1 1000 0.01 10 <out.vcf>`

I entered dummy values for min and max sv size and just used the values from the example usage on your github for min allele frequency and min number of reads. I am not entirely sure how to determine what values to input for these parameters.

The command executes successfully and produces an output but I do receive this warning/error message:

`Warning: Max size threshold set, TRA wont be reported as their size cannot be assesst.`

Additionally the <out.vcf> file has all SV's removed and only contains the header. There are 131704 SV's in my <input.vcf> and I receive the message `SVs ignored: 131704` resulting in an empty output file.

Is this due to an incorrect use of parameters and if so how can I correct these settings? Any help is greatly appreciated.

Best,
Alberto

**Comment by fritzsedlazeck** [comment]
Hi Alberto,
sorry this somehow slipped by. 
No this was not intended. The problem is/was that I assumed that the VCF included the number of supporting reads, which does not need to be the case. 
Thus, the reads were filtered out. I updated the code. So please go ahead and clone and build it again and give it a try. 

Let me know if that resolves the problem. 

Thanks
Fritz

**Comment by alpreyes** [comment]
Hi Fritz,

Yes this fixed my problem. Now, changing values for the parameters does alter how SV's are filtered. 

Thank you very much!

Alberto

**Comment by dKlee99** [comment]
Hi,

I'm encountering the same issue here. Has the code been updated and fixed? I have installed the newest version of SURVIVOR and still facing the same error. Thank you!

Best,
DK
